# Generated by Django 3.2.7 on 2022-06-18 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task11_lesson15', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
            ],
        ),
    ]
